version: '3'
services:
  app:
    container_name: nodejs-letsencrypt
    build: .
    image: nodejs-letsencrypt:latest
    ports:
      - "8080:8080"

networks:
  default:
    external:
      name: nginx-proxy