version: '3'
services:
  app:
    container_name: nodejs-letsencrypt
    build: .
    image: nodejs-letsencrypt:latest
    ports:
      - "8080:8080"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/log/letsencrypt:/var/log/letsencrypt

networks:
  default:
    external:
      name: nginx-proxy